// Code generated by uagen from rules/*.yaml; DO NOT EDIT.

package uax

var builtinEngineRules = []rule{
	{pattern: "AppleWebKit", matchType: matchExact, engineName: "WebKit"},
	{pattern: "Gecko", matchType: matchExact, engineName: "Gecko"},
	{pattern: "Trident", matchType: matchExact, engineName: "Trident"},
	{pattern: "Presto", matchType: matchExact, engineName: "Presto"},
	{pattern: "EdgeHTML", matchType: matchExact, engineName: "EdgeHTML"},
	{pattern: "Blink", matchType: matchExact, engineName: "Blink"},
	{pattern: "Goanna", matchType: matchExact, engineName: "Goanna"},
	{pattern: "KHTML", matchType: matchExact, engineName: "KHTML"},
	{pattern: "NetFront", matchType: matchExact, engineName: "NetFront"},
	{pattern: "NetSurf", matchType: matchExact, engineName: "NetSurf"},
	{pattern: "Servo", matchType: matchExact, engineName: "Servo"},
	{pattern: "Flow", matchType: matchExact, engineName: "Flow"},
	{pattern: "LibWeb", matchType: matchExact, engineName: "LibWeb"},
	{pattern: "xChaos_Arachne", matchType: matchExact, engineName: "Arachne"},
	{pattern: "LibWeb+LibJs", matchType: matchExact, engineName: "LibWeb"},
	{pattern: "ArkWeb", matchType: matchExact, engineName: "ArkWeb"},
}
