package main

const fileHeader = `// Code generated by uagen from rules/*.yaml; DO NOT EDIT.

package uax

`

const browserTmpl = fileHeader + `var builtinBrowserRules = []rule{
{{- range .Rules}}
	{pattern: {{printf "%q" .Token}}, matchType: {{matchType .Match}}, browserName: {{printf "%q" .Browser}}, browserFamily: {{printf "%q" .Family}}, engineName: {{printf "%q" .Engine}}},
{{- end}}
}
`

const engineTmpl = fileHeader + `var builtinEngineRules = []rule{
{{- range .Rules}}
	{pattern: {{printf "%q" .Token}}, matchType: {{matchType .Match}}, engineName: {{printf "%q" .Engine}}},
{{- end}}
}
`

const botTmpl = fileHeader + `var builtinBotRules = []rule{
{{- range .Rules}}
	{pattern: {{printf "%q" .Token}}, matchType: {{matchType .Match}}, botName: {{printf "%q" .Name}}, botClass: {{botClass .Class}}, botVendor: {{printf "%q" .Vendor}}, botIsVerified: {{.Verified}}},
{{- end}}
}
`

const deviceTmpl = fileHeader + `var builtinDeviceRules = []rule{
{{- range .Rules}}
	{pattern: {{printf "%q" .Token}}, matchType: {{matchType .Match}}, deviceType: {{printf "%q" .Type}}, deviceVendor: {{printf "%q" .Vendor}}, deviceModel: {{printf "%q" .Model}}},
{{- end}}
}
`

const appTmpl = fileHeader + `var builtinAppRules = []rule{
{{- range .Rules}}
	{pattern: {{printf "%q" .Token}}, matchType: {{matchType .Match}}, appName: {{printf "%q" .Name}}, appKind: {{printf "%q" .Kind}}},
{{- end}}
}
`
