package main

const fileHeader = `// Code generated by uagen from rules/*.yaml; DO NOT EDIT.

package uax

`

const browserTmpl = fileHeader + `{{if .HasRegex}}import "regexp"

{{end}}var builtinBrowserRules = []rule{
{{- range .Rules}}
	{pattern: {{printf "%q" .Token}}, matchType: {{matchType .Match}}, browserName: {{printf "%q" .Browser}}, browserFamily: {{printf "%q" .Family}}, engineName: {{printf "%q" .Engine}}{{if eq .Match "regex"}}, re: regexp.MustCompile({{printf "%q" .Token}}){{end}}},
{{- end}}
}
`

const engineTmpl = fileHeader + `{{if .HasRegex}}import "regexp"

{{end}}var builtinEngineRules = []rule{
{{- range .Rules}}
	{pattern: {{printf "%q" .Token}}, matchType: {{matchType .Match}}, engineName: {{printf "%q" .Engine}}{{if eq .Match "regex"}}, re: regexp.MustCompile({{printf "%q" .Token}}){{end}}},
{{- end}}
}
`

const botTmpl = fileHeader + `{{if .HasRegex}}import "regexp"

{{end}}var builtinBotRules = []rule{
{{- range .Rules}}
	{pattern: {{printf "%q" .Token}}, matchType: {{matchType .Match}}, botName: {{printf "%q" .Name}}, botClass: {{botClass .Class}}, botVendor: {{printf "%q" .Vendor}}, botIsVerified: {{.Verified}}{{if eq .Match "regex"}}, re: regexp.MustCompile({{printf "%q" .Token}}){{end}}},
{{- end}}
}
`

const deviceTmpl = fileHeader + `{{if .HasRegex}}import "regexp"

{{end}}var builtinDeviceRules = []rule{
{{- range .Rules}}
	{pattern: {{printf "%q" .Token}}, matchType: {{matchType .Match}}, deviceType: {{printf "%q" .Type}}, deviceVendor: {{printf "%q" .Vendor}}, deviceModel: {{printf "%q" .Model}}{{if eq .Match "regex"}}, re: regexp.MustCompile({{printf "%q" .Token}}){{end}}},
{{- end}}
}
`

const appTmpl = fileHeader + `{{if .HasRegex}}import "regexp"

{{end}}var builtinAppRules = []rule{
{{- range .Rules}}
	{pattern: {{printf "%q" .Token}}, matchType: {{matchType .Match}}, appName: {{printf "%q" .Name}}, appKind: {{printf "%q" .Kind}}{{if eq .Match "regex"}}, re: regexp.MustCompile({{printf "%q" .Token}}){{end}}},
{{- end}}
}
`
